name: Instrumentation tests

on:
  push:
    branches:
      - feature/marcos/add_maestro_to_ci
  schedule:
    - cron: '0 4 * * *' # run at 3 AM UTC
  workflow_dispatch:

jobs:
  instrumentation_tests:
    runs-on: macos-latest
    name: Instrumentation tests
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Decode keys
        uses: davidSchuppa/base64Secret-toFile-action@v1
        with:
          secret: ${{ secrets.FAKE_RELEASE_PROPERTIES }}
          fileName: ddg_android_build.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v1
        with:
          secret: ${{ secrets.FAKE_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-emul-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          ndk: 21.0.6113669
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Android checks
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          ndk: 21.0.6113669
          arch: x86_64
          profile: Nexus 5
          force-avd-creation: false
          emulator-options: -no-window -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew installPlayRelease && cd maestro && for i in *.yaml; do maestro test "$i"; done;

      - name: Bundle the Android CI checks report
        if: always()
        run: find . -type d -name 'reports' | zip -@ -r android-checks-report.zip

      - name: Upload the Android CI checks report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: android-checks-report
          path: android-checks-report.zip